# Generated by Django 5.1.1 on 2024-10-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_case_url_title_alter_case_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
