# Generated by Django 5.1.1 on 2024-10-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_alter_case_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='requirements',
        ),
    ]
