# Generated by Django 5.1.1 on 2024-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_remove_case_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='requierments',
            field=models.TextField(null=True),
        ),
    ]
