# Generated by Django 5.1.1 on 2024-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_client_image_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='testimonial',
            field=models.TextField(blank=True),
        ),
    ]
