# Generated by Django 5.1.1 on 2024-10-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0010_client_description_client_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bussiness_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='bussiness_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
