# Generated by Django 5.1.1 on 2024-10-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0012_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='linked_in',
            new_name='linkedin',
        ),
    ]
