# Generated by Django 5.1.1 on 2024-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0013_rename_linked_in_teammember_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='small_overview',
            field=models.TextField(default='small_overview'),
        ),
    ]
