# Generated by Django 5.1.1 on 2024-10-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0015_teammember_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default='ahmadazizbelkahia@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(default='+216 22 222 222', max_length=50),
        ),
    ]
