# Generated by Django 5.1.1 on 2024-10-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0016_teammember_bio_teammember_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='skills_bio',
            field=models.TextField(default='test'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Pages.teammember')),
            ],
        ),
    ]
