# Generated by Django 5.1.1 on 2024-10-30 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0018_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='blogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Pages.block')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_title', models.SlugField()),
                ('image', models.ImageField(upload_to='image/')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('read_time', models.CharField(max_length=50)),
                ('mini_description', models.TextField()),
                ('tags', models.CharField(max_length=50)),
                ('quote', models.TextField()),
                ('quote_image', models.ImageField(upload_to='image/')),
                ('quote_name', models.CharField(max_length=50)),
                ('quote_role', models.CharField(max_length=50)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Pages.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Pages.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Pages.post')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='Pages.post'),
        ),
    ]
