# Generated by Django 5.1.1 on 2024-10-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0019_block_blogimage_post_comment_block_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
