# Generated by Django 5.1.2 on 2024-10-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0020_block_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='out_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
