# Generated by Django 5.1.2 on 2024-10-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0021_service_out_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='quote_image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
